env:
  browser: true
  commonjs: true
  es2021: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
parser: babel-eslint
parserOptions:
  ecmaVersion: 12
  sourceType: module
  ecmaFeatures:
    arrowFunctions: true
    binaryLiterals: true
    blockBindings: true
    classes: true
    jsx: true
  
plugins:
  - react
rules:
  indent:
  - error
  - tab
  linebreak-style:
  - error
  - unix
  quotes:
  - error
  - single
  semi:
  - error
  - always
  no-mixed-spaces-and-tabs:
    - 2
    - smart-tabs