env:
  browser: false
  commonjs: true
  es2021: true
  node: true
  mocha: true
extends: 
  - 'eslint:recommended'
plugins:
  - 'mocha'
parserOptions:
  ecmaVersion: 12
rules:
  indent:
  - error
  - tab
  linebreak-style:
  - error
  - unix
  quotes:
  - error
  - single
  semi:
  - error
  - always
